### ISSUE TITLE
Issue in Optional Parameters

### ISSUE THREAD

**Issue by ramesh-subramani** [Liverpool-Victoria/gradle-dbdeploy-plugin#2]
Optional Parameters like changeLogTableName, lastChangeToApply are not getting set. The issue seems to be in AbstractDbDeployTask. It contains a check like -

if (delimiter) {
 dbDeploy.setDelimiter(getDelimiter())
 }

shouldn't this be

if (getDelimiter()) {
 dbDeploy.setDelimiter(getDelimiter())
 }

**Comment by willis7** [comment]
Ahh yes, very good spot. Poor form on my part not testing this.

**Comment by willis7** [comment]
I have made the change to the code and published a version 1.3.
[Gradle Portal](https://plugins.gradle.org/plugin/com.lv.dbdeploy)
